---

- name: Copy nginx exporter script
  ansible.builtin.template:
    src: "nginx_exporter"
    dest: /usr/local/bin/nginx_exporter
    mode: 0755
    owner: root
    group: root

- name: Copy nginx exporter script
  ansible.builtin.template:
    src: "nginx_exporter.service"
    dest: /etc/systemd/system/nginx_exporter.service
    mode: 0644
    owner: root
    group: root

- name: Restart nginx exporter service is restarted
  ansible.builtin.service:
    name: Nginx_exporter
    state: restarted
    enabled: true
  changed_when: false

- name: Wait for nginx exporter to become ready
  ansible.builtin.wait_for:
    host: "{{ nginx_exporter_server_bind }}"
    port: "{{ nginx_exporter_server_port }}"
    state: started
    delay: 5
    connect_timeout: 15
    timeout: 300
