---
# handlers for ansible-role-docker-nginx_exporter

- name: Restart nginx_exporter
  ansible.builtin.service:
    name: Nginx_exporter
    state: restarted
    enabled: true

- name: Start nginx_exporter
  ansible.builtin.service:
    name: Nginx_exporter
    state: started
    enabled: true

- name: Reload nginx_exporter
  ansible.builtin.service:
    name: Nginx_exporter
    state: reloaded
    enabled: true
